import Foundation

/// Maps Apple user IDs from CloudKit to Supabase auth UUIDs.
///
/// The mapping file is a JSON array of objects with `apple_user_id` and `supabase_user_id` keys.
/// This file is generated by having each beta tester sign in with Supabase, then recording
/// the association between their Apple user identifier and the new Supabase auth UUID.
public struct UserMapping: Sendable {
    /// Individual mapping entry from the JSON file.
    public struct Entry: Codable, Sendable, Equatable {
        public let appleUserID: String
        public let supabaseUserID: String
        public let displayName: String?

        public init(appleUserID: String, supabaseUserID: String, displayName: String? = nil) {
            self.appleUserID = appleUserID
            self.supabaseUserID = supabaseUserID
            self.displayName = displayName
        }

        private enum CodingKeys: String, CodingKey {
            case appleUserID = "apple_user_id"
            case supabaseUserID = "supabase_user_id"
            case displayName = "display_name"
        }
    }

    private let entriesByAppleID: [String: Entry]

    /// All entries in the mapping.
    public var entries: [Entry] {
        Array(entriesByAppleID.values)
    }

    /// All Apple user IDs that have a mapping.
    public var appleUserIDs: Set<String> {
        Set(entriesByAppleID.keys)
    }

    public init(entries: [Entry]) {
        var dict = [String: Entry]()
        for entry in entries {
            dict[entry.appleUserID] = entry
        }
        self.entriesByAppleID = dict
    }

    /// Loads the mapping from a JSON file at the given path.
    public static func load(from path: String) throws -> UserMapping {
        let url = URL(fileURLWithPath: path)
        guard FileManager.default.fileExists(atPath: path) else {
            throw MigrationError.mappingFileNotFound(path: path)
        }
        let data = try Data(contentsOf: url)
        let entries = try JSONDecoder().decode([Entry].self, from: data)
        guard !entries.isEmpty else {
            throw MigrationError.invalidMappingFile(reason: "mapping file is empty")
        }
        return UserMapping(entries: entries)
    }

    /// Returns the Supabase UUID for a given Apple user ID, or throws.
    public func supabaseUserID(for appleUserID: String) throws -> String {
        guard let entry = entriesByAppleID[appleUserID] else {
            throw MigrationError.missingUserMapping(appleUserID: appleUserID)
        }
        return entry.supabaseUserID
    }

    /// Returns the Supabase UUID if available, nil otherwise.
    public func supabaseUserIDOrNil(for appleUserID: String) -> String? {
        entriesByAppleID[appleUserID]?.supabaseUserID
    }

    /// Returns the entry for a given Apple user ID.
    public func entry(for appleUserID: String) -> Entry? {
        entriesByAppleID[appleUserID]
    }
}
